export const unitOfMeasures = [
  { value: 'acre', displayText: 'Acre' },
  { value: 'bag', displayText: 'Bag' },
  { value: 'barrel (uk petroleum)', displayText: 'Barrel (UK Petroleum)' },
  { value: 'barrel (us)', displayText: 'Barrel (US)' },
  { value: 'bottle', displayText: 'Bottle' },
  { value: 'box', displayText: 'Box' },
  {
    value: 'british thermal unit (mean)',
    displayText: 'British Thermal Unit (Mean)',
  },
  { value: 'bundle', displayText: 'Bundle' },
  { value: 'calorie (mean)', displayText: 'Calorie (Mean)' },
  { value: 'carton', displayText: 'Carton' },
  { value: 'case', displayText: 'Case' },
  { value: 'centilitre', displayText: 'Centilitre' },
  { value: 'centimetre', displayText: 'Centimetre' },
  { value: 'crate', displayText: 'Crate' },
  { value: 'cubic foot', displayText: 'Cubic Foot' },
  { value: 'cubic inch', displayText: 'Cubic Inch' },
  { value: 'cubic metre', displayText: 'Cubic Metre' },
  { value: 'cubic millimetre', displayText: 'Cubic Millimetre' },
  { value: 'cubic yard', displayText: 'Cubic Yard' },
  { value: 'cylinder', displayText: 'Cylinder' },
  { value: 'day', displayText: 'Day' },
  { value: 'drum', displayText: 'Drum' },
  { value: 'each', displayText: 'Each' },
  { value: 'foot', displayText: 'Foot' },
  { value: 'gram', displayText: 'Gram' },
  { value: 'hectare', displayText: 'Hectare' },
  { value: 'hour', displayText: 'Hour' },
  { value: 'inch', displayText: 'Inch' },
  { value: 'kilogram', displayText: 'Kilogram' },
  { value: 'kilometre', displayText: 'Kilometre' },
  { value: 'litre', displayText: 'Litre' },
  { value: 'lot', displayText: 'Lot' },
  { value: 'mandays', displayText: 'Man Days' },
  { value: 'metre', displayText: 'Metre' },
  { value: 'milligram', displayText: 'Milligram' },
  { value: 'millimetre', displayText: 'Millimetre' },
  { value: 'minute [unit of time]', displayText: 'Minute' },
  { value: 'month', displayText: 'Month' },
  { value: 'ounce', displayText: 'Ounce' },
  { value: 'packet', displayText: 'Packet' },
  { value: 'piece', displayText: 'Piece' },
  { value: 'pieces', displayText: 'Pieces' },
  { value: 'pound', displayText: 'Pound' },
  { value: 'second [unit of time]', displayText: 'Second' },
  { value: 'square metre', displayText: 'Square Metre' },
  { value: 'tonne (metric ton)', displayText: 'Tonne (Metric)' },
  { value: 'unit', displayText: 'Unit' },
  { value: 'week', displayText: 'Week' },
  { value: 'year', displayText: 'Year' },
];
