import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import { incoTerms } from '@/enums/incoTerms';
import { FormikProps } from 'formik';
import { InvoiceFormValues } from '@/types/invoiceTypes';
import { useTranslation } from 'react-i18next';
import { Label } from '@/components/ui/label';
import { CalendarIcon, X } from 'lucide-react';
import { format } from 'date-fns';

interface InvoiceDetailsGridProps {
  formik: FormikProps<InvoiceFormValues>;
  t: ReturnType<typeof useTranslation>[0];
}

export const InvoiceDetailsGrid = ({ formik, t }: InvoiceDetailsGridProps) => {
  return (
    <div className='grid grid-cols-1 lg:grid-cols-3 gap-4'>
      <div>
        <Label
          htmlFor='invoiceNumber'
          className='text-sm text-gray-700 mb-1'
        >
          {t('invoices.form.invoiceNumberLabel')}
        </Label>
        <Input
          className='bg-blue-50 h-10'
          placeholder='INV-123456'
          name='invoiceNumber'
          value={formik.values.invoiceNumber}
          onChange={formik.handleChange}
        />
        <div className='text-xs text-gray-400 mt-1'>
          {t('invoices.form.autoGeneratedIfBlank')}
        </div>

        <Label
          htmlFor='invoiceDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.invoiceDateLabel')}
        </Label>
        <div className='relative'>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant='outline'
                className='w-full justify-start text-left font-normal bg-blue-50 h-10'
              >
                <CalendarIcon className='mr-2 h-4 w-4' />
                {formik.values.invoiceDate
                  ? format(
                      new Date(formik.values.invoiceDate + 'T00:00:00'),
                      'PPP'
                    )
                  : t('invoices.form.chooseDate')}
              </Button>
            </PopoverTrigger>
            <PopoverContent className='w-auto p-0'>
              <Calendar
                mode='single'
                selected={
                  formik.values.invoiceDate
                    ? new Date(formik.values.invoiceDate + 'T00:00:00')
                    : undefined
                }
                onSelect={(date) => {
                  if (date) {
                    const year = date.getFullYear();
                    const month = String(date.getMonth() + 1).padStart(2, '0');
                    const day = String(date.getDate()).padStart(2, '0');
                    formik.setFieldValue(
                      'invoiceDate',
                      `${year}-${month}-${day}`
                    );
                  }
                }}
                initialFocus
              />
            </PopoverContent>
          </Popover>
          {formik.values.invoiceDate && (
            <button
              type='button'
              onClick={(e) => {
                e.stopPropagation();
                formik.setFieldValue('invoiceDate', '');
              }}
              className='absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600'
            >
              <X className='h-4 w-4' />
            </button>
          )}
        </div>
        {formik.touched.invoiceDate && formik.errors.invoiceDate ? (
          <div className='text-sm text-red-500'>
            {t(String(formik.errors.invoiceDate))}
          </div>
        ) : (
          !formik.values.invoiceDate && (
            <div className='text-xs text-gray-400 mt-1'>
              {t('invoices.form.chooseDate')}
            </div>
          )
        )}

        <Label
          htmlFor='supplyDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.supplyDateLabel')}
        </Label>
        <div className='relative'>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant='outline'
                className='w-full justify-start text-left font-normal bg-blue-50 h-10'
              >
                <CalendarIcon className='mr-2 h-4 w-4' />
                {formik.values.supplyDate
                  ? format(
                      new Date(formik.values.supplyDate + 'T00:00:00'),
                      'PPP'
                    )
                  : t('invoices.form.chooseDate')}
              </Button>
            </PopoverTrigger>
            <PopoverContent className='w-auto p-0'>
              <Calendar
                mode='single'
                selected={
                  formik.values.supplyDate
                    ? new Date(formik.values.supplyDate + 'T00:00:00')
                    : undefined
                }
                onSelect={(date) => {
                  if (date) {
                    const year = date.getFullYear();
                    const month = String(date.getMonth() + 1).padStart(2, '0');
                    const day = String(date.getDate()).padStart(2, '0');
                    formik.setFieldValue(
                      'supplyDate',
                      `${year}-${month}-${day}`
                    );
                  }
                }}
                initialFocus
              />
            </PopoverContent>
          </Popover>
          {formik.values.supplyDate && (
            <button
              type='button'
              onClick={(e) => {
                e.stopPropagation();
                formik.setFieldValue('supplyDate', '');
              }}
              className='absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600'
            >
              <X className='h-4 w-4' />
            </button>
          )}
        </div>
        {formik.touched.supplyDate && formik.errors.supplyDate ? (
          <div className='text-sm text-red-500'>
            {t(String(formik.errors.supplyDate))}
          </div>
        ) : (
          !formik.values.supplyDate && (
            <div className='text-xs text-gray-400 mt-1'>
              {t('invoices.form.chooseDate')}
            </div>
          )
        )}
      </div>

      <div>
        <Label
          htmlFor='incoterms'
          className='block text-sm text-gray-700 mb-1'
        >
          {t('invoices.form.incoTerms')}:
        </Label>
        <div className='flex items-center gap-3'>
          <Select
            value={formik.values.incoterms}
            onValueChange={(v) => formik.setFieldValue('incoterms', v)}
          >
            <SelectTrigger className='bg-blue-50 h-10 w-28'>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {incoTerms.map((it) => (
                <SelectItem
                  key={it.value}
                  value={it.value}
                >
                  {it.displayText}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Input
            className='bg-blue-50 h-10 flex-1'
            placeholder={t('invoices.form.location')}
            name='location'
            value={formik.values.location}
            onChange={formik.handleChange}
            disabled={formik.values.incoterms === 'na'}
          />
        </div>

        <Label
          htmlFor='dueDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.dueDate')}:
        </Label>
        <div className='relative'>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant='outline'
                className='w-full justify-start text-left font-normal bg-blue-50 h-10'
              >
                <CalendarIcon className='mr-2 h-4 w-4' />
                {formik.values.dueDate
                  ? format(new Date(formik.values.dueDate + 'T00:00:00'), 'PPP')
                  : t('invoices.form.chooseDate')}
              </Button>
            </PopoverTrigger>
            <PopoverContent className='w-auto p-0'>
              <Calendar
                mode='single'
                selected={
                  formik.values.dueDate
                    ? new Date(formik.values.dueDate + 'T00:00:00')
                    : undefined
                }
                onSelect={(date) => {
                  if (date) {
                    const year = date.getFullYear();
                    const month = String(date.getMonth() + 1).padStart(2, '0');
                    const day = String(date.getDate()).padStart(2, '0');
                    formik.setFieldValue('dueDate', `${year}-${month}-${day}`);
                  }
                }}
                initialFocus
              />
            </PopoverContent>
          </Popover>
          {formik.values.dueDate && (
            <button
              type='button'
              onClick={(e) => {
                e.stopPropagation();
                formik.setFieldValue('dueDate', '');
              }}
              className='absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600'
            >
              <X className='h-4 w-4' />
            </button>
          )}
        </div>
        {formik.touched.dueDate && formik.errors.dueDate ? (
          <div className='text-sm text-red-500'>
            {t(String(formik.errors.dueDate))}
          </div>
        ) : (
          !formik.values.dueDate && (
            <div className='text-xs text-gray-400 mt-1'>
              {t('invoices.form.chooseDate')}
            </div>
          )
        )}

        <Label
          htmlFor='supplyEndDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.supplyEndDate')}:
        </Label>
        <div className='relative'>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant='outline'
                className='w-full justify-start text-left font-normal bg-blue-50 h-10'
              >
                <CalendarIcon className='mr-2 h-4 w-4' />
                {formik.values.supplyEndDate
                  ? format(
                      new Date(formik.values.supplyEndDate + 'T00:00:00'),
                      'PPP'
                    )
                  : t('invoices.form.chooseDate')}
              </Button>
            </PopoverTrigger>
            <PopoverContent className='w-auto p-0'>
              <Calendar
                mode='single'
                selected={
                  formik.values.supplyEndDate
                    ? new Date(formik.values.supplyEndDate + 'T00:00:00')
                    : undefined
                }
                onSelect={(date) => {
                  if (date) {
                    const year = date.getFullYear();
                    const month = String(date.getMonth() + 1).padStart(2, '0');
                    const day = String(date.getDate()).padStart(2, '0');
                    formik.setFieldValue(
                      'supplyEndDate',
                      `${year}-${month}-${day}`
                    );
                  }
                }}
                initialFocus
              />
            </PopoverContent>
          </Popover>
          {formik.values.supplyEndDate && (
            <button
              type='button'
              onClick={(e) => {
                e.stopPropagation();
                formik.setFieldValue('supplyEndDate', '');
              }}
              className='absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600'
            >
              <X className='h-4 w-4' />
            </button>
          )}
        </div>
        {!formik.values.supplyEndDate && (
          <div className='text-xs text-gray-400 mt-1'>
            {t('invoices.form.chooseDate')}
          </div>
        )}
      </div>

      <div>
        <Label
          htmlFor='contractId'
          className='block text-sm text-gray-700 mb-1'
        >
          {t('invoices.form.contractId')}:
        </Label>
        <Input
          className='bg-blue-50 h-10'
          placeholder={t('invoices.form.contractId')}
          name='contractId'
          value={formik.values.contractId}
          onChange={formik.handleChange}
        />

        <Label
          htmlFor='customerPoNumber'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.customerPoNumber')}:
        </Label>
        <Input
          className='bg-blue-50 h-10'
          placeholder={t('invoices.customerPoNumber')}
          name='customerPoNumber'
          value={formik.values.customerPoNumber}
          onChange={formik.handleChange}
        />
      </div>
    </div>
  );
};
