import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { incoTerms } from '@/enums/incoTerms';
import { FormikProps } from 'formik';
import { InvoiceFormValues } from '@/types/invoiceTypes';
import { useTranslation } from 'react-i18next';
import { Label } from '@/components/ui/label';

interface InvoiceDetailsGridProps {
  formik: FormikProps<InvoiceFormValues>;
  t: ReturnType<typeof useTranslation>[0];
}

export const InvoiceDetailsGrid = ({ formik, t }: InvoiceDetailsGridProps) => {
  return (
    <div className='grid grid-cols-1 lg:grid-cols-3 gap-4'>
      <div>
        <Label
          htmlFor='invoiceNumber'
          className='text-sm text-gray-700 mb-1'
        >
          {t('invoices.form.invoiceNumberLabel')}
        </Label>
        <Input
          className='bg-blue-50 h-10'
          placeholder='INV-123456'
          name='invoiceNumber'
          value={formik.values.invoiceNumber}
          onChange={formik.handleChange}
        />
        <div className='text-xs text-gray-400 mt-1'>
          {t('invoices.form.autoGeneratedIfBlank')}
        </div>

        <Label
          htmlFor='invoiceDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.invoiceDateLabel')}
        </Label>
        <Input
          className='bg-blue-50 h-10'
          type='date'
          name='invoiceDate'
          value={formik.values.invoiceDate}
          onChange={formik.handleChange}
          onBlur={formik.handleBlur}
        />
        {formik.touched.invoiceDate && formik.errors.invoiceDate ? (
          <div className='text-sm text-red-500'>
            {t(String(formik.errors.invoiceDate))}
          </div>
        ) : (
          !formik.values.invoiceDate && (
            <div className='text-xs text-gray-400 mt-1'>
              {t('invoices.form.chooseDate')}
            </div>
          )
        )}

        <Label
          htmlFor='supplyDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.supplyDateLabel')}
        </Label>
        <Input
          className='bg-blue-50 h-10'
          type='date'
          name='supplyDate'
          value={formik.values.supplyDate}
          onChange={formik.handleChange}
          onBlur={formik.handleBlur}
        />
        {formik.touched.supplyDate && formik.errors.supplyDate ? (
          <div className='text-sm text-red-500'>
            {t(String(formik.errors.supplyDate))}
          </div>
        ) : (
          !formik.values.supplyDate && (
            <div className='text-xs text-gray-400 mt-1'>
              {t('invoices.form.chooseDate')}
            </div>
          )
        )}
      </div>

      <div>
        <Label
          htmlFor='incoterms'
          className='block text-sm text-gray-700 mb-1'
        >
          {t('invoices.form.incoTerms')}:
        </Label>
        <div className='flex items-center gap-3'>
          <Select
            value={formik.values.incoterms}
            onValueChange={(v) => formik.setFieldValue('incoterms', v)}
          >
            <SelectTrigger className='bg-blue-50 h-10 w-28'>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {incoTerms.map((it) => (
                <SelectItem
                  key={it.value}
                  value={it.value}
                >
                  {it.displayText}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Input
            className='bg-blue-50 h-10 flex-1'
            placeholder={t('invoices.form.location')}
            name='location'
            value={formik.values.location}
            onChange={formik.handleChange}
            disabled={formik.values.incoterms === 'na'}
          />
        </div>

        <Label
          htmlFor='dueDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.dueDate')}:
        </Label>
        <Input
          className='bg-blue-50 h-10'
          type='date'
          name='dueDate'
          value={formik.values.dueDate}
          onChange={formik.handleChange}
          onBlur={formik.handleBlur}
        />
        {formik.touched.dueDate && formik.errors.dueDate ? (
          <div className='text-sm text-red-500'>
            {t(String(formik.errors.dueDate))}
          </div>
        ) : (
          !formik.values.dueDate && (
            <div className='text-xs text-gray-400 mt-1'>
              {t('invoices.form.chooseDate')}
            </div>
          )
        )}

        <Label
          htmlFor='supplyEndDate'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.form.supplyEndDate')}:
        </Label>
        <Input
          className='bg-blue-50 h-10'
          type='date'
          name='supplyEndDate'
          value={formik.values.supplyEndDate}
          onChange={formik.handleChange}
        />
        {!formik.values.supplyEndDate && (
          <div className='text-xs text-gray-400 mt-1'>
            {t('invoices.form.chooseDate')}
          </div>
        )}
      </div>

      <div>
        <Label
          htmlFor='contractId'
          className='block text-sm text-gray-700 mb-1'
        >
          {t('invoices.form.contractId')}:
        </Label>
        <Input
          className='bg-blue-50 h-10'
          placeholder={t('invoices.form.contractId')}
          name='contractId'
          value={formik.values.contractId}
          onChange={formik.handleChange}
        />

        <Label
          htmlFor='customerPoNumber'
          className='block text-sm text-gray-700 mt-4 mb-1'
        >
          {t('invoices.customerPoNumber')}:
        </Label>
        <Input
          className='bg-blue-50 h-10'
          placeholder={t('invoices.customerPoNumber')}
          name='customerPoNumber'
          value={formik.values.customerPoNumber}
          onChange={formik.handleChange}
        />
      </div>
    </div>
  );
};
